// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture


StructuredBuffer<float3> staticBuffer;
StructuredBuffer<float> interactionMatrix;
RWStructuredBuffer<float3> theBuffer;
RWStructuredBuffer<float3> debugBuffer;

//varibles for shader to work
uint whichParticle;
float2 Result;
float3 DebugVar;
float distanceTo;
float2 directionTo;

float forceRange;
float forceStrengthMultiplier;
float repelWhenCloseStrengthMultiplier;
float dampingMultiplier;

//basic functions
float DistanceTo(float2 item1, float2 item2)
{
    return sqrt(pow((item1.x - item2.x), 2) + pow(item1.y - item2.y,2));

}

float2 DirectionTo(float2 item1, float2 item2)
{
    return normalize(item1 - item2);
}


//function that attracts particles together
static const uint howManyParticleTypesExist = 2;
void attractToType(uint indexOfthingAtrractedTo, int2 typesAllowed)
{
    bool isIn = false;
    for (uint j = 0; j < howManyParticleTypesExist || isIn == false; j++)
    {
        if (staticBuffer[indexOfthingAtrractedTo].z == typesAllowed[j])
        {
            isIn = true;
        }
        if (isIn == false && j == (howManyParticleTypesExist - 1))
        {
            return;
        }
    }

    distanceTo = DistanceTo(float2(staticBuffer[whichParticle].x, staticBuffer[whichParticle].y), float2(staticBuffer[indexOfthingAtrractedTo].x, staticBuffer[indexOfthingAtrractedTo].y));
    directionTo = DirectionTo(float2(staticBuffer[indexOfthingAtrractedTo].x, staticBuffer[indexOfthingAtrractedTo].y), float2(staticBuffer[whichParticle].x, staticBuffer[whichParticle].y));
    
    if (distanceTo < forceRange && distanceTo != 0 && isIn == true)
    {
            //attract to other things
        Result += directionTo * (distanceTo * forceStrengthMultiplier);
            
            // repel when close
        Result += (-directionTo) * (repelWhenCloseStrengthMultiplier / max(0.01, float(pow(distanceTo, 2))));
            
            //dampining 
        Result += -dampingMultiplier * (Result * abs(Result));
            
            //change force based on interaction matrix
        Result = Result * interactionMatrix[(staticBuffer[whichParticle].z - 1) * howManyParticleTypesExist + (staticBuffer[indexOfthingAtrractedTo].z - 1)];
        
            //set buffer
        theBuffer[whichParticle] = float3(theBuffer[whichParticle].x, theBuffer[whichParticle].y, 0) + float3(Result.x, Result.y, 0);
    }
}



[numthreads(8,8,1)]
void CSMain(uint3 id : SV_GroupThreadID, uint3 groupID : SV_GroupID)
{
    //varibles that deffine particles
    forceRange = 5;
    forceStrengthMultiplier = 1;
    repelWhenCloseStrengthMultiplier = 1;
    dampingMultiplier = 0.01;
    
    uint count;
    uint stride;
    
    Result = float2(0, 0);
    
    staticBuffer.GetDimensions(count, stride);
    
    whichParticle = ((id.y * 8) + id.x) + (groupID.x * 64);
    
    int2 typesAlowed;
    int2 Red = int2(1, 2);
    int2 Yellow = int2(1, 2);

    switch (staticBuffer[whichParticle].z)
    {
        case 1:
            typesAlowed = int2(Red.x, Red.y);
            break;
        case 2:
            typesAlowed = int2(Yellow.x, Yellow.y);
            break;
    }
    
    
    for (uint i = 0; i < count; i++)
    {
        attractToType(i, typesAlowed);
    }
    
    theBuffer[whichParticle] += float3(0, 0, staticBuffer[whichParticle].z);
        
  
}
